name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/forforksake/platform_manifest_twrp_omni -b twrp-9.0
  DEVICE: mustang
  DT_LINK: https://github.com/forforksake/android_device_amazon_mustang
  DT_PATH: device/amazon/kyoto
  TARGET: recoveryimage
  VENDOR: amazon
  TZ: Europe/London
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            sudo -E apt-get clean
            sudo apt update
            sudo apt install bc build-essential zip curl libstdc++6 git wget 2to3 python2-minimal python2 dh-python python-is-python3 gcc clang rsync flex curl bison liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev aria2 -y
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -c -q --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
             repo sync --force-sync
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch omni_$DEVICE-eng && export ALLOW_MISSING_DEPENDENCIES=true && mka recoveryimage
             
       - name: Upload recovery image 
         run: |
              cd work/out/target/product/$DEVICE
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof recovery.img && ./transfer gof ramdisk-recovery.img
              ./transfer wet recovery.img && ./transfer wet ramdisk-recovery.img

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/recovery.img

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip
